config/routes.rb
Rails.application.routes.draw do
  # Pages
  root to: 'pages#home'
  resources :pages, only: [:index]
  
  # Users
  devise_for :users
  resources :profiles, only: [:index, :show]

  # Players
  resources :players, only: [:index, :update, :create]
  
  # Friends
  get '/my_friends', to: 'profiles#my_friends', as: :my_friends
  post '/profiles/:id/add', to: 'profiles#add_friend', as: :add_friend
  post '/profiles/:id/accept', to: 'profiles#accept_friend', as: :accept_friend
  post '/profiles/:id/decline', to: 'profiles#decline_friend', as: :decline_friend

  # Matches
  resources :matches do
    # Join match
    resources :players, only: [:create]

    # API for forums
    resources :forums, only: [:new, :create], defaults: { format: :json }
    post 'winner', to: 'matches#winner', as: :winner
  end
  get '/tagged', to: 'matches#index', as: :tagged

  # Categories
  resources :categories, only: [:new, :create, :edit, :update, :destroy ]
  
  # Forums
  resources :forums, only: [:index], defaults: { format: :json }

  # Rankings / Leaderboards
  get 'rankings', to: "rankings#index", as: :rankings

  # Contact Us
  get 'contacts', to: "pages#contacts", as: :contacts
end

app/models/profile.rb
class Profile < User
  include PgSearch
  pg_search_scope :search_by_user_details,
    against: [:name, :city],
      using: { tsearch: { prefix: true } }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_profile, only: [:add_friend, :accept_friend, :decline_friend]

  def index
    search = false

    if params.key?(:search)
      search = params[:search]
      if search.key?(:query)
        search = params[:search][:query]
        search = search.nil? && search == "" ? false : true
      end
    end

    if search == true && params[:search][:query].empty? == false
      @profiles = Profile.search_by_user_details(params[:search][:query])
    else
      @profiles = policy_scope(Profile).order(created_at: :desc)
    end
  end

  def my_friends
     @profiles = current_user.friends
     authorize @profiles
  end

  def show
    @profile = User.find(params[:id])
    authorize @profile
    @categories = @profile.categories.select(:name).distinct
    if current_user
      @matches = Match.where("status = ? AND user_id = ?", "open", current_user.id).order(created_at: :desc)
    end
    @player = Player.new
    # @ranking = Category.ranking_position(@matches[0].tag_list[0], current_user)
  end

  def add_friend
    current_user.friend_request(@profile)
    redirect_to profiles_path
  end

  def accept_friend
    current_user.accept_request(@profile)
    redirect_to my_friends_path
  end

   def decline_friend
    current_user.decline_request(@profile)
    redirect_to my_friends_path
  end

  private

  def set_profile
    authorize @profile = Profile.find(params[:id])
  end

end

app/views/profiles/index.html.erb
<div class="container">

  <div class="search" id="buddies-index-searchbar">
    <h2 class="text-center" style="margin: 10vh 0 4vh;">Find Buddies</h2>
    <div class="text-center mr-0" id="form-search">
      <%= simple_form_for :search, defaults: { required: false }, url: profiles_path, method: "GET", html: { class: 'text-center mr-0', style: "" } do |f| %>
      <%= f.input :query, label: false, placeholder: "Search for buddies", input_html: {value: ""} %>
      <i class="fas fa-search" id="icon-search" style="position: relative; top: -48px; right: -140px; color: rgba(0,0,0,0.5);"></i>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center" id="profile-index-buddy">
    <% if @profiles != [] %>
      <% @profiles.each do |profile| %>
          <% unless profile.name == current_user.name %>
          <div class="col-sm-8 offset-lg-0 col-lg-6">
            <div class="card mb-3 border-0" style="border-radius: 15px; box-shadow: 1px 1px 5px rgba(0,0,0,0.2);">
              <div class="row no-gutters", style="border-radius: 30px">
                <div class="col-md-4">
                  <p class="mb-0"><%= image_tag (cl_image_path profile.photo), crop: :fill, style:"object-fit:cover; height: 170px; width: 170px", class: "rounded-circle center p-3" %></p>
                </div>
                <div class="col-md-8 d-flex flex-column justify-content-between">
                  <div class="card-body">
                    <div>
                      <h5 class="card-title"><%= profile.name.titlecase %></h5>
                      <p class="card-text"><%= profile.city %></p>
                    </div>
                    <div class="mt-3">
                      <% unless profile.friends.any? { |f| f == current_user } %>
                        <% if profile.requested_friends.any? { |f| f == current_user } %>
                          <%= link_to "Pending", add_friend_path(profile), method: :post, class: "disabled btn btn-secondary  " %>
                        <% else %>
                          <%= link_to "Connect", add_friend_path(profile), method: :post, class: "btn btn-success" %>
                        <% end %>

                      <% end %>
                      <%= link_to "View Profile", profile_path(profile), class: "btn btn-link" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <h4>"Sorry, user is not found"</h4>
    <% end %>
</div>

</div>

app/views/profiles/my_friends.html.erb
<div class="container">
  <div class="profile-friends">
    <% if policy(@profiles).my_friends? %>
      <div class="search navigations">
        <h3 id="request-get" class="active">Request Received</h3>
        <h3 id="all-friends">My Sport Buddies</h3>
        <h3 id="request-sent">Request Sent</h3>
      </div>

      <div id="friends-toPlace" class="row">
        <% if current_user.requested_friends != [] %>
          <% current_user.requested_friends.each do |friend| %>
            <div class="offset-sm-2 col-sm-8 offset-lg-0 col-lg-6">
              <div class="card mb-3 border-0" style="border-radius: 15px; box-shadow: 1px 1px 5px rgba(0,0,0,0.2);">
                <div class="row no-gutters", style="border-radius: 30px">
                  <div class="col-md-4">
                    <p class="mb-0"><%= image_tag (cl_image_path friend.photo), crop: :fill, style:"object-fit:cover; height: 170px; width: 170px", class: "rounded-circle center p-3" %></p>
                  </div>
                  <div class="col-md-8 d-flex flex-column justify-content-between">
                    <div class="card-body">
                      <div>
                        <h5 class="card-title"><%= friend.name.titlecase %></h5>
                        <p class="card-text"><%= friend.city %></p>
                      </div>
                    </div class="">
                    <div class="m-3">
                          <%= link_to "Accept", accept_friend_path(friend), method: :post, class: "btn btn-success" %>
                          <%= link_to "Decline", decline_friend_path(friend), method: :post, class: "btn btn-danger" %>
                      <%= link_to "View Profile", profile_path(friend), class: "btn btn-link" %>
                    </div>
                  </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <h4 class="text-center" style="width: 100%;">"You have no pending friend requests"</h4>
        <% end %>

        <!-- TODO: not done -->
        <!-- <div class="row">
          <% @profiles.each do |profile| %>
            <div class="col-sm-12 col-md-6">
              <p><%= profile.name %>TODO: styling</p>
            </div>
          <% end %>
        </div> -->

        <!-- END friends-toPlace -->
      </div>
    <% end %>
  </div>
</div>

<script>
  const addClassSelected = (target) => {
    // take parent class -> get children -> remove classes for all children
    const children = target.parentElement.children;
    const childAmount = target.parentElement.childElementCount;
    for (let i=0; i<childAmount; i++) {
      children[i].classList.remove("active");
    }
    // add class
    target.classList.add("active");
  };

  this.addEventListener("click", (e) => {
    const whereToShow = document.querySelector("#friends-toPlace");
    const id = e.target.id;
    if (id === "request-get") {
      addClassSelected(e.target);
      whereToShow.innerHTML = "";
      whereToShow.insertAdjacentHTML("beforeend", `
      <% if current_user.requested_friends != [] %>
      <% current_user.requested_friends.each do |friend| %>
        <div class="offset-sm-2 col-sm-8 offset-lg-0 col-lg-6">
          <div class="card mb-3 border-0" style="border-radius: 15px; box-shadow: 1px 1px 5px rgba(0,0,0,0.2);">
            <div class="row no-gutters", style="border-radius: 30px">
              <div class="col-md-4">
                <p class="mb-0"><%= image_tag (cl_image_path friend.photo), crop: :fill, style:"object-fit:cover; height: 170px; width: 170px", class: "rounded-circle center p-3" %></p>
              </div>
              <div class="col-md-8 d-flex flex-column justify-content-between">
                <div class="card-body">
                  <div>
                    <h5 class="card-title"><%= friend.name.titlecase %></h5>
                    <p class="card-text"><%= friend.city %></p>
                  </div>
                </div class="">
                <div class="m-3">
                      <%= link_to "Accept", accept_friend_path(friend), method: :post, class: "btn btn-success" %>
                      <%= link_to "Decline", decline_friend_path(friend), method: :post, class: "btn btn-danger" %>
                  <%= link_to "View Profile", profile_path(friend), class: "btn btn-link" %>
                </div>
              </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <h4 class="text-center" style="width: 100%;">"You have no pending friend requests"</h4>
    <% end %>
      `);
    }
    else if (id === "all-friends") {
      addClassSelected(e.target);
      whereToShow.innerHTML = "";
      whereToShow.insertAdjacentHTML("beforeend", `
        <% if @profiles != [] %>
          <% @profiles.each do |friend| %>
          <div class="offset-sm-2 col-sm-8 offset-lg-0 col-lg-6">
              <div class="card mb-3 border-0" style="border-radius: 15px; box-shadow: 1px 1px 5px rgba(0,0,0,0.2);">
                <div class="row no-gutters", style="border-radius: 30px">
                  <div class="col-md-4">
                    <p class="mb-0"><%= image_tag (cl_image_path friend.photo), crop: :fill, style:"object-fit:cover; height: 170px; width: 170px", class: "rounded-circle center p-3" %></p>
                  </div>
                  <div class="col-md-8 d-flex flex-column justify-content-between">
                    <div class="card-body">
                      <div>
                        <h5 class="card-title"><%= friend.name.titlecase %></h5>
                        <p class="card-text"><%= friend.city %></p>
                      </div>
                    </div class="">
                    <div class="m-3">
                      <%= link_to "View Profile", profile_path(friend), class: "btn btn-success" %>
                    </div>
                  </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <h4 class="text-center" style="width: 100%;">"You have no friends"</h4>
        <% end %>
      `);
    }
    else if (id === "request-sent") {
      addClassSelected(e.target);
      whereToShow.innerHTML = "";
      whereToShow.insertAdjacentHTML("beforeend", `
        <% if current_user.pending_friends != [] %>
          <% current_user.pending_friends.each do |friend| %>
            <div class="offset-sm-2 col-sm-8 offset-lg-0 col-lg-6">
              <div class="card mb-3 border-0" style="border-radius: 15px; box-shadow: 1px 1px 5px rgba(0,0,0,0.2);">
                <div class="row no-gutters", style="border-radius: 30px">
                  <div class="col-md-4">
                    <p class="mb-0"><%= image_tag (cl_image_path friend.photo), crop: :fill, style:"object-fit:cover; height: 170px; width: 170px", class: "rounded-circle center p-3" %></p>
                  </div>
                  <div class="col-md-8 d-flex flex-column justify-content-between">
                    <div class="card-body">
                      <div>
                        <h5 class="card-title"><%= friend.name.titlecase %></h5>
                        <p class="card-text"><%= friend.city %></p>
                      </div>
                    </div class="">
                    <div class="m-3">
                          <%= link_to "Pending", accept_friend_path(friend), method: :post, class: "btn btn-secondary disabled" %>
                      <%= link_to "View Profile", profile_path(friend), class: "btn btn-link" %>
                    </div>
                  </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <h4 class="text-center" style="width: 100%;">"You have no pending sent friend requests"</h4>
        <% end %>
      `);
    };
  });
</script>

app/views/profiles/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 col-md-4">
    </div>
    <div class="col-12 col-md-8">
      <h2 class="mb-3" ><%= @profile.name.capitalize %>'s profile</h2>
    </div>
  </div>

  <% if policy(@profile).show? %>
    <!-- 1 - PROFILE IMG -->
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-4 p-0">
        <div class="d-flex justify-content-center p-0 mb-0", style="border-radius: 5px">
          <div class="rounded p-5">
            <div class="text-center mb-3">
              <%= image_tag (cl_image_path @profile.photo), crop: :fill, style:"object-fit:cover; height: 30vh; width: 30vh", class: "rounded-circle center" %>
            </div>
            <p class="font-weight-bold text-center mt-2 mb-0"><%= @profile.name.capitalize %></p>
            <p class="text-center mt-0 mb-3" style="font-size: 12px" ><%= @profile.city %></p>
            <% if (@profile.bio != "" && @profile.bio != nil) %>
              <p class="font-italic text-center mt-0">"<%= @profile.bio.capitalize %>"</p>
            <% else %>
              <p class="font-italic text-center mt-0"></p>
            <% end %>
          </div>
        </div>
      </div>

      <!-- 2 - OTHER INFO -->
      <div class="col-sm-12 col-md-12 col-lg-8" style="border-radius: 10px">
        <div class="pb-2 border-bottom border-info">
          <% if @profile == current_user %>
            <%= link_to "Edit my profile", edit_user_registration_path(current_user), class: "btn btn-link p-0" %>
          <% else %>
            <%= link_to  "See My Matches", matches_path(user_id: @profile.id), class: "btn btn-link p-0" %>
          <% end %>
        </div>

        <p class="text-center my-5" style="font-weight: bold; font-size: 24px;">My Sport Buddies</p>
        <div class="col mr-0">
          <div class= "row d-flex">
            <% User.find(params[:id]).friends.each do |friend| %>
              <div class="col-4 col-md-2">
                <div class="text-center">
                  <%= link_to (cl_image_tag friend.photo, crop: :fill, style:"object-fit:cover; height: 50px; width: 50px", class: "rounded-circle center justify-content-center text-center"), profile_path(friend)  %>
                </div>
                <div class="text-center mt-1 mb-4 text-black-50" style="">
                  <%= friend.name.split(" ")[0] %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <p class="pt-4 text-center pb-2 my-5" style="font-weight: bold; width: auto; font-size: 24px">My Dashboard</p>
        <div>
          <div class = "text-secondary" >
            <div class="row d-flex justify-content-around mt-5">
              <% @categories.each do |category| %>
                <div class="col-8 col-md-4 mb-4" style="text-align: center">
                  <div class="border border-light p-2 mb-5" style="box-shadow: 0 0 8px rgba(0,0,0,0.1);">
                    <p style="text-align: center; font-weight: bold"><%= category.name.capitalize %></p>
                    <p><i class="fas fa-medal text-warning"></i> <span class="font-weight-light"> Ranking : <%= Category.ranking_position(category.name, @profile.id)[:position] %></span></p>
                  <!--   <p><i class="fas fa-layer-group text-secondary"></i> <span class="font-weight-light"></span> </p> -->
                    <p><i class="fas fa-coins text-secondary"></i> <span class="font-weight-light"> Points : <%= Category.ranking_position(category.name, @profile.id)[:points]%></span></p>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="container" style="text-align: center">
  <% if user_signed_in? && params[:id].to_i != current_user.id %>
    <h2 class="text-center mb-4 mt-5" style="font-weight: bold">👊 Challenge Your Buddy 👊</h2>
    <div class="row justify-content-center">
      <div class="col-12 col-md-6 col-md-offset-3">
        <% if current_user %>
          <%= simple_form_for @player do |f| %>
            <%= f.input :match_id, label: "Choose the game:", include_blank: false, collection: @matches,label_method: :description, value_method: :id%>
            <%= f.hidden_field :challenged, value: @profile.id %>

            <%= f.submit "Challenge!", class: "btn btn-success mt-4 mb-5" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>