config/routes.rb
Rails.application.routes.draw do
  # Pages
  root to: 'pages#home'
  resources :pages, only: [:index]
  
  # Users
  devise_for :users
  resources :profiles, only: [:index, :show]

  # Players
  resources :players, only: [:index, :update, :create]
  
  # Friends
  get '/my_friends', to: 'profiles#my_friends', as: :my_friends
  post '/profiles/:id/add', to: 'profiles#add_friend', as: :add_friend
  post '/profiles/:id/accept', to: 'profiles#accept_friend', as: :accept_friend
  post '/profiles/:id/decline', to: 'profiles#decline_friend', as: :decline_friend

  # Matches
  resources :matches do
    # Join match
    resources :players, only: [:create]

    # API for forums
    resources :forums, only: [:new, :create], defaults: { format: :json }
    post 'winner', to: 'matches#winner', as: :winner
  end
  get '/tagged', to: 'matches#index', as: :tagged

  # Categories
  resources :categories, only: [:new, :create, :edit, :update, :destroy ]
  
  # Forums
  resources :forums, only: [:index], defaults: { format: :json }

  # Rankings / Leaderboards
  get 'rankings', to: "rankings#index", as: :rankings

  # Contact Us
  get 'contacts', to: "pages#contacts", as: :contacts
end

app/views/pages/contacts.html.erb
<div class="container" id="contact-us">
    <h1>Meet The Creators</h1>
    <div class="row">
        <!-- STEVEN -->
        <div class="col-sm-12 col-md-6 col-lg-3">
            <div>
                <div>
                    <%= image_tag "stevenly.png" %>
                </div>
                <h5> Steven Ly </h5>
                <p>"Back-End Developer"</p>
                <ul class="personal-links">
                    <li>
                        <a href="https://github.com/shiwenly"><i class="fab fa-github"></i></a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/in/steven-ly-8b731733/"><i class="fab fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- FELIPE -->
        <div class="col-sm-12 col-md-6 col-lg-3">
            <div>
                <div>
                    <%= image_tag "felipe.jpg" %>
                </div>
                <h5> Felipe Roschel </h5>
                <p>"Back-End Developer"</p>
                <ul class="personal-links">
                    <li>
                        <a href="https://github.com/feliperoschel"><i class="fab fa-github"></i></a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/in/feliperoschel/"><i class="fab fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- RICHARD -->
        <div class="col-sm-12 col-md-6 col-lg-3">
            <div>
                <div>
                    <%= image_tag "richard.jpg" %>
                </div>
                <h5> Richard Sugianto So</h5>
                <p>"Lead Developer / Front-End"</p>
                <ul class="personal-links">
                    <li>
                        <a href="https://github.com/scorcious"><i class="fab fa-github"></i></a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/in/richardsugiantoso/"><i class="fab fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- STEVEN -->
        <div class="col-sm-12 col-md-6 col-lg-3">
            <div>
                <div>
                    <%= image_tag "stevy.jpg" %>
                </div>
                <h5> Steven Chareonbood </h5>
                <p>"Project Manager / Front-End"</p>
                <ul class="personal-links">
                    <li>
                        <a href="https://github.com/chareonbood"><i class="fab fa-github"></i></a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/in/schareonbood/"><i class="fab fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- ADD MARGIN BOTTOM HERE -->
    <h1>Scan the QR Code Below</h1>
    <div class="row" id="qrcode">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <!-- TODO: WeChat Group-->
            <h3>WeChat Group</h3>
            <div>
                <%= image_tag "wechatQR.jpg" %>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6">
            <!-- TODO: Website-->
            <h3>Our Website</h3>
            <div>
                <%= image_tag "webQR.png", id:"webQR" %>
            </div>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="pages-home">

    <div style="margin-top: -20vh; position: relative; background: url('https://images.unsplash.com/photo-1542446655-53a7e25c8fe2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1795&q=80'); background-position: center; background-size: top; background-repeat: no-repeat; height: 27em; width: 100%; padding: 20vh 0 58vh 0; background-size: cover;">
      <section style="margin-top: 14vh; position: relative; z-index: 2; margin-bottom: em; text-align: center;">
          <h1 class="mesg-top" style="color: #2ED573; font-weight: bold">Find sports games</h1>
          <h1 style="margin-bottom: 1em; color: rgb(230,230,230);">around you</h1>
          <%= form_for :search, defaults: { required: false }, url: matches_path, method: "GET", html: { class: '' } do |f| %>
          <section style="position: relative; text-align:center;">
            <%= f.text_field :query, label: false, placeholder: "Search...", input_html: {value: ""}, style: "width: 19em; border-radius: 9999px; border-style: none; height: 2.5em; position: absolute; margin-left: auto; margin-right: auto; left: 0; right: 0; padding-left: 16px; opacity: 0.8;" %>
            <i class="fas fa-search" id="icon-search" style="position: relative; top: 8px; right: -110px; color: rgba(0,0,0,0.5);"></i>
          </section>
          <% end %>
      </section>
      <div style="position: absolute; background-image: linear-gradient(to bottom, rgba(0,0,0, 0.6), rgba(255,255,255, 0.05)); top: 0; left: 0; right: 0; bottom: 0; width: 100%;"></div>
    </div>



    <div class="container">
        <h2 style="color: rgb(50,50,50)">How it works</h2>
        <div class="row text-center">

          <div class="col-12 col-md-12 col-lg-3">
            <div class="parent px-4 pt-4 pb-0 mt-5">
              <div class="child border rounded-circle p-1" style="opacity: 1;">
                <p class="child-num">1</p>
              </div>
              <i class="icon-green fas fa-user-plus m-5", style="font-size: 100px"></i>
              <p style="color: rgba(0,0,0,0.75)">Create or sign-up for a game. As simple as that!</p>
              <p style="color:white; font-size: 14px">.</p>
            </div>
          </div>

          <div class="col-12 col-md-12 col-lg-3">
            <div class="parent px-4 pt-4 pb-0 mt-5">
              <div class="child border rounded-circle p-1">
                <p class="child-num">2</p>
              </div>
              <i class="icon-green far fa-smile m-5", style="font-size: 100px"></i>
              <p style="color: rgba(0,0,0,0.75)">Play the challenge and earn glory and honor</p>
              <p style="font-size: 14px; color:rgb(150, 150, 150);">(win: 30 points / draw: 10 points)</p>
            </div>
          </div>

          <div class="col-12 col-md-12 col-lg-3">
            <div class="parent px-4 pt-4 pb-0 mt-5">
              <div class="child border rounded-circle p-1">
                <p class="child-num">3</p>
              </div>
              <i class="icon-green fas fa-chart-line m-5", style="font-size: 100px"></i>
              <p style="color: rgba(0,0,0,0.75)">Measure your progress to get better</p>
              <p style="color:white; font-size: 14px">.</p>
            </div>
          </div>
        </div>

        <h2 style="color: rgb(50,50,50)">Categories</h2>
        <div class="row"> <!-- TODO: TAGS FOR SPORTS AND LINKS -->
            <div class="recommended col-sm-12 col-md-6 col-lg-3">
                <img src="https://images.unsplash.com/photo-1552667466-07770ae110d0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
                <h3><%= link_to "Football", tagged_path(tag: "football") %></h3>
            </div>
            <div class="recommended col-sm-12 col-md-6 col-lg-3">
                <img src="https://images.unsplash.com/photo-1521412644187-c49fa049e84d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80" alt="">
                <h3><%= link_to "Basketball", tagged_path(tag: "basketball") %></h3>
            </div>
            <div class="recommended col-sm-12 col-md-6 col-lg-3">
                <img src="https://images.unsplash.com/photo-1521537634581-0dced2fee2ef?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
                <h3><%= link_to "Badminton", tagged_path(tag: "badminton") %></h3>
            </div>
            <div class="recommended col-sm-12 col-md-6 col-lg-3">
                <img src="https://images.unsplash.com/photo-1482614312710-79c1d29bda2a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="">
                <h3><%= link_to "Tennis", tagged_path(tag: "tennis") %></h3>
            </div>
            <div class="recommended col-sm-12 col-md-6 col-lg-3">
                <img src="https://images.unsplash.com/photo-1556732282-595ef530909c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
                <h3><%= link_to "Volleyball", tagged_path(tag: "volleyball") %></h3>
            </div>
            <div class="recommended col-sm-12 col-md-6 col-lg-3">
                <img src="https://images.unsplash.com/photo-1543928612-0b3a1a5d9223?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
                <h3><%= link_to "Pool", tagged_path(tag: "pool") %></h3>
            </div>
            <div class="recommended col-sm-12 col-md-6 col-lg-3">
                <img src="https://images.unsplash.com/photo-1521800641212-77d98bb90d21?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" alt="">
                <h3><%= link_to "Boxing", tagged_path(tag: "boxing") %></h3>
            </div>
            <div class="recommended col-sm-12 col-md-6 col-lg-3">
                <img src="https://images.unsplash.com/photo-1459865264687-595d652de67e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="">
                <h3><%= link_to  "See All", matches_path %></h3>
            </div>
        </div>

        <h2 style="color: rgb(50,50,50)">Discover Games</h2>
        <div class="row paintings justify-content-center">
            <% @matches.each do |m| %>
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <div class="card rounded shadow-sm border-0 m-3" style="box-shadow: 15 15 15 15; margin: 0;">
                        <%= cl_image_tag m.photo, style: "height: 220px; object-fit: cover; object-position: center" %>
                        <div class="card-body">
                            <h5 class="text-truncate"><%= m.description %></h5>
                            <div class="see-match">
                                <p>Coming in: <%= (m.date - Date.today).to_i %> days</p>
                                <%= link_to  "See More", match_path(m), style: "font-size: 14px; text-decoration: underline;", class: "stretched-link" %>
                            </div>
                        </div>
                    </div>
                </div>

            <% end %>
        </div>
    </div>
</div>

app/views/pages/index.html.erb
<div class="container">
    <div class="pages-index">
        <div class="search">
            <h2 class="text-center">Searh for users, matches and sports...</h2>
            <%= simple_form_for :search, defaults: { required: false }, url: matches_path, method: "GET", html: { class: '' } do |f| %>
            <%= f.input :query, label: false, placeholder: "Search for matches", input_html: {value: ""} %>
            <% end %>
        </div>

    </div>
</div>