config/routes.rb
Rails.application.routes.draw do
  # Pages
  root to: 'pages#home'
  resources :pages, only: [:index]
  
  # Users
  devise_for :users
  resources :profiles, only: [:index, :show]

  # Players
  resources :players, only: [:index, :update, :create]
  
  # Friends
  get '/my_friends', to: 'profiles#my_friends', as: :my_friends
  post '/profiles/:id/add', to: 'profiles#add_friend', as: :add_friend
  post '/profiles/:id/accept', to: 'profiles#accept_friend', as: :accept_friend
  post '/profiles/:id/decline', to: 'profiles#decline_friend', as: :decline_friend

  # Matches
  resources :matches do
    # Join match
    resources :players, only: [:create]

    # API for forums
    resources :forums, only: [:new, :create], defaults: { format: :json }
    post 'winner', to: 'matches#winner', as: :winner
  end
  get '/tagged', to: 'matches#index', as: :tagged

  # Categories
  resources :categories, only: [:new, :create, :edit, :update, :destroy ]
  
  # Forums
  resources :forums, only: [:index], defaults: { format: :json }

  # Rankings / Leaderboards
  get 'rankings', to: "rankings#index", as: :rankings

  # Contact Us
  get 'contacts', to: "pages#contacts", as: :contacts
end

app/models/match.rb
class Match < ApplicationRecord
  acts_as_taggable_on :tags
  belongs_to :user
  has_many :forums, dependent: :destroy
  has_many :players, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  validates :date, :city, :location, :description, :time, :level, presence: true
  validates :number_of_players, numericality: { greater_than: 0 , even: true}

  include PgSearch
  pg_search_scope :search_by_game_details,
    against: [:location, :description, :level, :number_of_players, :city],
      using: { tsearch: { prefix: true } }

  def full?
    self.players.where.not(status: 'declined').count >= self.number_of_players
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  def index
    # TODO: SEARCH
    # 1. show user's matches
    # 2. search fn() for all sports, and tags
    # 3. get all tags
    search = false

    if params.key?(:search)
      search = params[:search]
      if search.key?(:query)
        search = params[:search][:query]
        search = search.nil? && search == "" ? false : true
      end
    end

    # INIT
    @all_matches_signed_up = []
    @past_matches = []
    @user_name = params["user_id"].nil? ? "" : (User.find(params["user_id"]).name)

    # SEARCH FOR TAGS
    if params[:tag].present?
      # SHOW ALL MATCHES WITH THE TAG
      @matches = policy_scope(Match.tagged_with(params[:tag]))
      @matches = @matches.select { |match| match.status == "open" }
    elsif search == true && params[:search][:query].empty? == false
      @matches = policy_scope(Match.search_by_game_details(params[:search][:query])
        .where("status = ?", "open")
        .order(created_at: :desc))
      @show_user_match = !(params[:user_id].nil?)
      if @show_user_match
        @matches = Match.search_by_game_details(params[:search][:query])
        .where("user_id = ?", params["user_id"])
        .order(created_at: :desc)
        @all_matches_signed_up = find_all_matches_user_signed_up
        @past_matches = Match.where("status = ?", "past")
      end
    else
      # SHOW ALL MATCHES
      @matches = policy_scope(Match).order(created_at: :desc)
      @matches = Match.where("status = ?", "open").order(created_at: :desc)
      @show_user_match = !(params[:user_id].nil?)
      if @show_user_match
        @matches = Match.where("user_id = ?", params["user_id"]).order(created_at: :desc)
        @all_matches_signed_up = find_all_matches_user_signed_up
        @past_matches = Match.where("status = ?", "past")
      end
    end
  end

  def show
    authorize @match
    @players_a = @match.players.select { |player| player.team == "A" && player.status != "declined" }
    @players_b = @match.players.select { |player| player.team == "B" && player.status != "declined" }
    @forums = @match.forums.order(created_at: :desc)
    @forum = Forum.new
    @player = Player.new

    # friends available to challenge
    @friends = (current_user ? current_user.friends : [])
    if @friends != []
      @friends = @friends.reject do |f|
        player = Player.where("user_id = ? AND match_id = ?", f.id, @match.id)
        if player != []
          player.first.user == f
        end
      end
    end

    @array_A = @players_a.map do |player|
      player.user
    end
    @array_B = @players_b.map do |player|
      player.user
    end
    @all_players = @array_B + @array_A

    # challenges
    @challenges = []
    if current_user
      @challenges = policy_scope(Player).where("user_id = ? AND match_id = ? AND status = ?", current_user.id, @match.id, "pending")
      unless @challenges == []
        @challenger = User.find(@challenges[0].challenger_id)
      end
    end
  end

  def new
    authorize @match = Match.new
    @tags = Match.select(:city).distinct
  end

  def create
    authorize @match = Match.new(match_params)
    @match.user = current_user
    @match.status = "open"
    if @match.save
      # add
      add_team_to_player
      add_tags_to_match

      # redirect
      redirect_to @match
    else
      render :new
    end
  end

  def edit
    authorize @match
  end

  def update
    authorize @match
    if @match.update(match_params)
      redirect_to @match
    else
      render :edit
    end
  end

  def destroy
    authorize @match
    @match.status = "cancelled"
    @match.save
    redirect_to root_path
  end

  def winner
    @match = Match.find(params[:match_id])
    authorize @match
    @match.winner = params[:match]["winner"]
    @match.save
    calculate_points
    redirect_to match_path(@match)
  end


  def calculate_points
    @match = Match.find(params[:match_id])
    authorize @match

    winner_team = @match.winner.downcase
    winner_points = 30
    draw_points = 10
    category_match = @match.tags[0].name.downcase
    level_match = @match.tags[2].name.downcase

    @match.players.each do |player|
      category_user = Category.find_or_create_by(user_id: player.user_id, name: category_match, level: level_match)
      if player.team.downcase == winner_team
        category_user.points += winner_points
      elsif winner_team == "draw"
        category_user.points += draw_points
      end
      category_user.save
    end
  end

  private

  def match_params
    params.require(:match).permit(
      :date,
      :city,
      :location,
      :description,
      :time,
      :level,
      :number_of_players,
      :photo,
      :tag_list
    )
  end

  def set_match
    @match = Match.find(params[:id])
  end

  def add_tags_to_match
    tags = match_params[:tag_list].split(',')
    tags << match_params[:city]
    tags << match_params[:level]
    @match.tag_list.add(tags)
    @match.save
  end

  def add_team_to_player
    @player = Player.new
    @player.user = current_user
    @player.status = "accepted"
    @player.team = 'A'
    @player.match = @match
    authorize @player
    @player.save!
  end

  def find_all_matches_user_signed_up
    all_matches_signed_up = []
    Match.all.each do |m|
      if m.status != "past" && m.status != "cancelled"
        m.players.each do |p|
        # finding if current user is signed up these events
          if p.user.id == params["user_id"].to_i
            all_matches_signed_up << m
          end
        end
      end
    end
    return all_matches_signed_up
  end
end

app/views/matches/edit.html.erb
<div class="container center">
  <div class="border center">
    <%= simple_form_for [@match] do |f| %>
      <%= f.input :date %>
      <%= f.input :location %>
      <%= f.input :description %>
      <%= f.input :time %>
      <%= f.input :level, collection: %w(beginner intermediate advanced) %>
      <%= f.input :number_of_players %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit "Update", class: "btn btn-success" %>
      <%= link_to "Games", matches_path, class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/matches/index.html.erb
<div class="container match-index">
  <% if @show_user_match %>
    <div class="search navigations">
      <h3 id="matches-current" class="active">All Games</h3>
      <h3 id="hosted">Hosted Games</h3>
      <h3 id="matches-past">Past Games</h3>
    </div>
  <% else %>
    <div class="search">
      <h2 class="text-center">Find Games Around you</h2>
      <div class="text-center mr-0" id="form-search">
        <%= simple_form_for :search, defaults: { required: false }, url: matches_path, method: "GET", html: { class: 'text-center mr-0', style: "" } do |f| %>
        <%= f.input :query, label: false, placeholder: "Search for games", input_html: {value: ""}, class: "mr-0" %>
        <i class="fas fa-search" id="icon-search" style="position: relative; top: -48px; right: -140px; color: rgba(0,0,0,0.5);"></i>
      </div>
      <% end %>
    </div>
  <% end %>
  <div class="row" id='match-js'>
    <% if @show_user_match %>
      <% if @all_matches_signed_up != [] # if im not looking for a specific user's match %>
        <% @all_matches_signed_up.each do |match| %>
          <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="content">
              <%= cl_image_tag match.photo, class: "rounded-top" %>
              <div class="mt-2">
                <p class="text-left mb-2"><i class="fas fa-map-marker-alt"></i> <%= match.user.city %></p>
                <h5 class="text-left text-truncate ml-1"><%= match.description %></h5>
              </div>

              <div class="mt-0">
                <p>Level: <%= match.level %></p>
                <p>Max Players: <%= match.number_of_players %></p>
                <div class="d-flex px-0">
                  <p style="color:rgba(0,0,0,0.6)"><i class="fas fa-calendar-alt"></i> <%= match.date.strftime("%d/%m/%Y") %> -  <%= match.time.strftime("%H:%M") %></p>
                  <%= link_to "Details", match_path(match), class: "my-0 ml-5 stretched-link", style:"font-size: 14px; text-decoration: underline" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="no-match">
          <div>
            <h4> "No matches are found" </h4>
            <%= link_to  "Browse Matches", matches_path, class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <% if @matches.count != 0 %>
        <% @matches.each do |match| %>
          <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="content">
              <%= cl_image_tag match.photo, class: "rounded-top" %>
              <div class="mt-2">
                <p class="text-left mb-2"><i class="fas fa-map-marker-alt"></i> <%= match.user.city %></p>
                <h5 class="text-left text-truncate ml-1"><%= match.description %></h5>
              </div>
              <div class="mt-0">
                <p>Level: <%= match.level %></p>
                <p>Max Players: <%= match.number_of_players %></p>
                <div class="d-flex px-0">
                  <p style="color:rgba(0,0,0,0.6)";><i class="fas fa-calendar-alt"></i> <%= match.date.strftime("%d/%m/%Y") %> -  <%= match.time.strftime("%H:%M") %></p>
                  <%= link_to "Details", match_path(match), class: "my-0 ml-5 stretched-link", style: "font-size: 14px; text-decoration: underline;" %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
      <% else %>
        <h4 class="text-center" style="width: 100%;">"Sorry, there is no match available"</h4>
      <% end %>
    <% end %>
  </div>
</div>

<script>
  const addClassSelected = (target) => {
    // take parent class -> get children -> remove classes for all children
    const children = target.parentElement.children;
    const childAmount = target.parentElement.childElementCount;
    for (let i=0; i<childAmount; i++) {
      children[i].classList.remove("active");
    }
    // add class
    target.classList.add("active");
  }

  this.addEventListener("click", (e) => {
    // INIT
    const whereToShow = document.querySelector("#match-js");
    const id = e.target.id;

    // INJECT HTML
    if (id === "matches-current") {
      addClassSelected(e.target);
      whereToShow.innerHTML = "";
      whereToShow.insertAdjacentHTML("beforeend", `
      <% if @all_matches_signed_up != [] %>
        <% @all_matches_signed_up.each do |match| %>

        <div class="col-sm-12 col-md-6 col-lg-4">
          <div class="content">
            <%= cl_image_tag match.photo, class: "rounded-top" %>
            <div class="mt-2">
              <p class="text-left mb-2"><i class="fas fa-map-marker-alt"></i> <%= match.user.city %></p>
              <h5 class="text-left text-truncate ml-1"><%= match.description %></h5>
            </div>
            <div class="mt-0">
              <p>Level: <%= match.level %></p>
              <p>Max Players: <%= match.number_of_players %></p>
              <div class="d-flex px-0">
                <p style="color:rgba(0,0,0,0.6)";><i class="fas fa-calendar-alt"></i> <%= match.date.strftime("%d/%m/%Y") %> -  <%= match.time.strftime("%H:%M") %></p>
                <%= link_to "Details", match_path(match), class: "my-0 ml-5 stretched-link", style: "font-size: 14px; text-decoration: underline;" %>
              </div>
            </div>
          </div>
        </div>

        <% end %>
      <% else %>
        <div class="no-match">
          <div>
            <h4> "No matches are found!" </h4>
            <%= link_to  "Browse Matches", matches_path, class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
      `)
    }
    else if (id === "hosted") {
      addClassSelected(e.target);
      whereToShow.innerHTML = "";
      whereToShow.insertAdjacentHTML("beforeend", `
      <% if @matches != [] %>
        <% @matches.each do |match| %>

        <div class="col-sm-12 col-md-6 col-lg-4">
          <div class="content">
            <%= cl_image_tag match.photo, class: "rounded-top" %>
            <div class="mt-2">
              <p class="text-left mb-2"><i class="fas fa-map-marker-alt"></i> <%= match.user.city %></p>
              <h5 class="text-left text-truncate ml-1"><%= match.description %></h5>
            </div>
            <div class="mt-0">
              <p>Level: <%= match.level %></p>
              <p>Max Players: <%= match.number_of_players %></p>
              <div class="d-flex px-0">
                <p style="color:rgba(0,0,0,0.6)";><i class="fas fa-calendar-alt"></i> <%= match.date.strftime("%d/%m/%Y") %> -  <%= match.time.strftime("%H:%M") %></p>
                <%= link_to "Details", match_path(match), class: "my-0 ml-5 stretched-link", style: "font-size: 14px; text-decoration: underline;" %>
              </div>
            </div>
          </div>
        </div>

        <% end %>
      <% else %>
        <div class="no-match">
          <div>
            <h4> "<%= @user_name %> have not host any matches" </h4>
            <%= link_to  "Host a match", new_match_path, class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
      `)
    }
    else if (id === "matches-past") {
      addClassSelected(e.target);
      whereToShow.innerHTML = "";
      whereToShow.insertAdjacentHTML("beforeend", `
      <% if @past_matches != [] %>
        <% @past_matches.each do |match| %>

        <div class="col-sm-12 col-md-6 col-lg-4">
          <div class="content">
            <%= cl_image_tag match.photo, class: "rounded-top" %>
            <div class="mt-2">
              <p class="text-left mb-2"><i class="fas fa-map-marker-alt"></i> <%= match.user.city %></p>
              <h5 class="text-left text-truncate ml-1"><%= match.description %></h5>
            </div>
            <div class="mt-0">
              <p>Level: <%= match.level %></p>
              <p>Max Players: <%= match.number_of_players %></p>
              <div class="d-flex px-0">
                <p style="color:rgba(0,0,0,0.6)";><i class="fas fa-calendar-alt"></i> <%= match.date.strftime("%d/%m/%Y") %> -  <%= match.time.strftime("%H:%M") %></p>
                <%= link_to "Details", match_path(match), class: "my-0 ml-5 stretched-link", style: "font-size: 14px; text-decoration: underline;" %>
              </div>
            </div>
          </div>
        </div>

        <% end %>
      <% else %>
        <div class="no-match">
          <div>
            <h4> "No past matches are found!" </h4>
            <%= link_to  "Browse Matches", matches_path, class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
      `)
    }
  })
</script>

app/views/matches/new.html.erb
<h1 class="text-center mt-5 mb-4">Create a Game</h1>
<div class="container center">
  <div class="row justify-content-center">
     <div class="col-12 col-md-6 col-lg-6">
      <div class="center">
        <%= simple_form_for [@match] do |f| %>
          <%= f.input :description, label: "Game Name" %>
          <%= f.input :city %>
          <%= f.input :location %>
          <%= f.input :date %>
          <%= f.input :time %>
          <%= f.input :level, collection: %w(beginner intermediate advanced) %>
          <%= f.input :number_of_players, input_html: { value: 2 } %>
          <%= f.input :tag_list, label: "Sports Category" %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit "Create", class: "btn btn-success mb-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/matches/show.html.erb
<div class="banner d-flex align-items-center justify-content-center" style="background: url(<%= (cl_image_tag @match.photo).match(/http\:(.)*"/)[0].gsub(/\"/, "") %>) no-repeat center center; background-size: cover; height: 70vh; position: relative" >
  <div style="background: rgba(0, 0, 0, 0.1); position:absolute; top:0; bottom:0;left:0;right:0">
  </div>
  <div style="position: absolute; z-index: 2">
    <h1 class="text-center" style="color: white"><%= @match.description %></h1>
    <p class="text-center" style="color: white"><%= @match.city %></p>
  </div>
</div>

<div class="container">
  <div class="py-5">
    <div class="row border rounded mt-5 mb-2 mx-0 p-3">
      <div class="col-sm-12 col-md-12 col-lg-5" id="match-show-event-details">
        <h5 class="text-left"><strong>Event details</strong></h5>
        <p style="font-size: 14px; margin: 20px 0 12px; text-transform: capitalize;"><span><i class="fas fa-map-marker-alt" style="font-size: 18px;"></i></span> <%= @match.location %></p>
        <p style="font-size: 14px; margin: 0 0 12px; text-transform: capitalize;"><span><i class="fas fa-calendar-alt" style="font-size: 18px;"></i></span> <%= @match.date.strftime("%d/%m/%Y") %> -  <%= @match.time.strftime("%H:%M") %></p>
        <% if (@match.date - Date.today).to_i >= 0 %>
          <p style="font-size: 14px; margin: 0 0 12px;">
            <span><i class="fas fa-clock" style="font-size: 18px; text-transform: capitalize;"></i></span>
            <% if (@match.date - Date.today).to_i == 0 %>
              Today
              <% else %>
              <%= (@match.date - Date.today).to_i %> Days
            <% end %>
          </p>
        <% end %>
        <p style="font-size: 14px; margin: 0 0 12px; text-transform: capitalize;"><span><i class="fas fa-signal" style="font-size: 18px;"></i></span> <%= @match.level %></p>
        <p class="mb-4", style="font-size: 14px ; margin: 0; text-transform: capitalize;"><span><i class="fas fa-user-circle" style="font-size: 18px;"></i></span> <%= @match.number_of_players %> members max.</p>
      </div>
      <div class="col-sm-12 col-md-12 col-lg-7">
      <h5 class="text-center"><strong>Team A</strong></h5>
      <div class="d-flex mb-5 round-plus-button justify-content-center">
        <% @players_a.each do |player| %>
          <% if player.status == "pending" %>
            <%= link_to (cl_image_tag player.user.photo, class: "pending rounded-circle mt-1", style: "width: 50px; height: 50px; object-fit: cover;"), profile_path(player.user) %>
          <% else %>
            <%= link_to (cl_image_tag player.user.photo, class: "rounded-circle mt-1", style: "width: 50px; height: 50px; object-fit: cover;"), profile_path(player.user) %>
          <% end %>
        <% end %>
        <!-- join button -->
        <% if @match.status == "open" && !(@all_players.any?{|user| user == current_user}) && !(@players_a.count >= (@match.number_of_players / 2)) %>
          <% if @challenges == [] %>
            <%= link_to "", match_players_path(@match, player: {team: 'A'}), method: :post, data: { confirm: 'Are you sure you want to join the team A?' }, class: "fas fa-plus-circle" %>
          <% end %>
        <% end %>
      </div>
      <h5 class="text-center"><strong>Team B</strong></h5>
      <div class="d-flex round-plus-button justify-content-center">
        <% @players_b.each do |player| %>
          <% if player.status == "pending" %>
            <%= link_to (cl_image_tag player.user.photo, class: "pending rounded-circle mt-1", style: "width: 50px; height: 50px; object-fit: cover;"), profile_path(player.user) %>
          <% else %>
            <%= link_to (cl_image_tag player.user.photo, class: "rounded-circle mt-1", style: "width: 50px; height: 50px; object-fit: cover;"), profile_path(player.user) %>
          <% end %>
        <% end %>
        <!-- join button -->
        <% if @match.status == "open" && !(@all_players.any?{|user| user == current_user}) && !(@players_b.count >= (@match.number_of_players / 2)) %>
          <% if @challenges == [] %>
            <%= link_to "", match_players_path(@match, player: {team: 'B'}), method: :post, data: { confirm: 'Are you sure you want to join the team B?' }, class: "fas fa-plus-circle" %>
          <% end %>
        <% end %>
      </div>
      </div>
    </div>
  </div>

  <div>
    <% if current_user && @match.status != "past" %>
      <% if @match.user == current_user %>
        <%= link_to "Edit", edit_match_path(@match), class: "btn btn-outline-success" %>
        <%= link_to "Cancel", match_path(@match), method: :delete, class: "btn btn-outline-danger" %>
      <% end %>
    <% end %>

    <!-- WINNER -->
    <% if @match.user == current_user && @match.status == "past" %>
      <h2 class="text-center mb-1 mt-5">Who is the winner :</h2>
      <% if @match.winner.nil? %>
        <div class="pb-4 challenge-btns d-flex justify-content-center">
          <div class="col-sm-12 col-md-10 p-0 mt-3">
            <%= link_to "Team A", match_winner_path(@match, match: {winner: 'A'}), method: :post, data: { confirm: 'Are you sure you want to choose the team A?' }, class: "btn btn-success" %>
            <%= link_to "Draw", match_winner_path(@match, match: {winner: 'Draw'}), method: :post, data: { confirm: 'Are you sure you want to choose draw?' }, class: "btn btn-outline-dark" %>
            <%= link_to "Team B", match_winner_path(@match, match: {winner: 'B'}), method: :post, data: { confirm: 'Are you sure you want to choose the team B?' }, class: "btn btn-primary" %>
          </div>
        </div>

      <% else %>
        <p>Team : <%= @match.winner %> </p>
      <% end %>
    <% end %>

    <!-- SHOW CHALLENGE REQUEST -->
    <% unless @challenges == [] %>
      <% if @challenges[0].match_id == @match.id %>
        <h2 class="text-center mt-5">👊 You Have a Challenge! 👊</h2>
        <h4 class="text-center mb-1 challenge-found">Challenger: <%= cl_image_tag @challenger.photo, class: "rounded-circle mt-1", style: "margin-left: 20px; width: 50px; height: 50px; object-fit: cover;" %> <%= link_to @challenger.name, profile_path(@challenger) %></h4>
        <div class="pb-4 challenge-btns d-flex justify-content-center">
          <div class="col-sm-12 col-md-10 p-0 mt-3">
            <%= link_to "Decline", player_path(@challenges[0], challenge: { status: 'declined' }), class: "btn btn-outline-danger", method: :put %>
            <%= link_to "Accept", player_path(@challenges[0], challenge: { status: 'accepted' }), class: "btn btn-outline-primary", method: :put %>
          </div>
        </div>
      <% end %>
    <% end %>

    <!-- Challenge buddy -->
    <% if @all_players.any?{|user| user == current_user} && user_signed_in? && !@match.full? && current_user.friends != [] && @match.status == "open"  && @friends != []%>
    <h2 class="text-center mb-1 mt-5">👊 Challenge Your Buddy 👊</h2>
    <div class="pb-4 challenge d-flex justify-content-center">
      <div class="col-sm-12 col-md-10 p-0">
        <%= simple_form_for [@match, @player] do |f| %>
          <%= f.input :user_id, label: "Choose your buddy:", include_blank: false, collection: @friends %>
          <%= f.submit "Challenge!", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>

  <!-- COMMENTS -->
  <h2 class="text-center mb-1 mt-5">Write a comment</h2>
  <div class="row justify-content-center">
    <div class="col-10">
      <div class="text-center">
      <% if policy(@forum).create? %>
        <%= simple_form_for [@match, @forum] do |f| %>
          <%= f.input :content, label: "Write your comment here:"%>
          <%= f.submit "save", class: "btn btn-success mt-0 mb-4", id: "refresh", data: { disable_with: false } %>
        <% end %>
      <% end %>
      </div>
      <div class="text-center">
        <div class="border" style="margin: 10vh 0; margin-top: 20px;padding: 20px;">
        <div id='forumstart'></div>
          <% if @forums != [] %>

            <% @forums.each do |comment| %>
            <% dayCount = (Time.new(Time.now - comment.created_at).day) -1 %>
            <div class="m-3 comments">
              <!-- IF DAYS == 0 THEN DONT SHOW DAYS -->
              <h5 class="m-0">
                <!-- TODO: CHANGE NAME INTO LINK TO USER -->
                <%= link_to comment.user.name.split(" ").first, profile_path(comment.user) %>
                <% if dayCount != 0 %> - <%= dayCount unless dayCount == 0 %> days ago<% else %>
                 - <%= comment.created_at.strftime("%H:%M") %> UTC
                 <% end %></h5>
              <p class="m-0"style="text-align: center; word-break: break-word"> <%= comment.content %> </p>
            </div>
            <% end %>
          <% else %>
            <div class="m-3 comments">
              <!-- IF DAYS == 0 THEN DONT SHOW DAYS -->
              <h5 class="m-0">"There is no comments"</h5>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>