config/routes.rb
Rails.application.routes.draw do
  # Pages
  root to: 'pages#home'
  resources :pages, only: [:index]
  
  # Users
  devise_for :users
  resources :profiles, only: [:index, :show]

  # Players
  resources :players, only: [:index, :update, :create]
  
  # Friends
  get '/my_friends', to: 'profiles#my_friends', as: :my_friends
  post '/profiles/:id/add', to: 'profiles#add_friend', as: :add_friend
  post '/profiles/:id/accept', to: 'profiles#accept_friend', as: :accept_friend
  post '/profiles/:id/decline', to: 'profiles#decline_friend', as: :decline_friend

  # Matches
  resources :matches do
    # Join match
    resources :players, only: [:create]

    # API for forums
    resources :forums, only: [:new, :create], defaults: { format: :json }
    post 'winner', to: 'matches#winner', as: :winner
  end
  get '/tagged', to: 'matches#index', as: :tagged

  # Categories
  resources :categories, only: [:new, :create, :edit, :update, :destroy ]
  
  # Forums
  resources :forums, only: [:index], defaults: { format: :json }

  # Rankings / Leaderboards
  get 'rankings', to: "rankings#index", as: :rankings

  # Contact Us
  get 'contacts', to: "pages#contacts", as: :contacts
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>mysportbuddies</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag %>
  </head>
  <body>
    <div class="wrapper">
      <!-- NAVBAR -->
      <nav class="navbar navbar-expand-lg navbar-light bg-nav-white">
        <a class="navbar-brand mb-2" href="/"><h4 class="logo">MYSPORTBUDDIES</h4></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="margin-right: 4vw;">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- IF USER IS LOGGED IN -->
        <% if current_user %>
        <div class="collapse navbar-collapse justify-content-end align-items-center" id="navbarSupportedContent">
          <ul class="navbar-nav mr-0">
            <div class="d-flex align-items-center pl-3 column-on-mobile">
              <!-- HOME PAGE -->
              <% if @white_links == true %>
                <li class="nav-item mx-4 mt-2">
                  <%= link_to  "Find buddies", profiles_path, style: "padding: 0;", class:"white" %>
                </li>
                <li class="nav-item mx-4 mt-2">
                  <%= link_to  "Browse games", matches_path, class:"white" %>
                </li>
              <% else %>
                <li class="nav-item mx-4 mt-2">
                  <%= link_to  "Find buddies", profiles_path, style: "padding: 0;" %><span class="sr-only">(current)</span>
                </li>
                <li class="nav-item mx-4 mt-2">
                  <%= link_to  "Browse games", matches_path %>
                </li>
              <% end %>
              <li class="nav-item mx-4 mt-2">
                <%= link_to  "Create game", new_match_path, class: "host-service" %>
              </li>
              <li class="nav-item dropdown">
                <!-- HIDE ON MOB -->
                <div class="hide-on-mobile nav-link dropdown-toggle p-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <div class="hide-on-mobile">
                    <%= image_tag (cl_image_path current_user.photo), crop: :fill, style: "height: 40px; width: 40px; object-fit: cover; border-radius: 50%" %>
                    <% if @total_counts != 0 %>
                      <div id="notif-div" style="position: absolute; top: 22px; right: -13px;">
                        <p id="notif-total"><%= @total_counts %></p>
                      </div>
                    <% end %>
                  </div>
                </div>
                <!-- PROFILE DROPDOWN -->
                <div class="dropdown-menu hidden-lg" aria-labelledby="navbarDropdown" style="top: 40px; left: -5em !important;">
                  <%= link_to "Profile", profile_path(current_user), class:"dropdown-item" %>
                  <%= link_to  "Buddies", my_friends_path, class:"dropdown-item" %>
                  <hr>
                  <%= link_to  "Games", matches_path(user_id: current_user.id), class:"dropdown-item" %>
                  <%= link_to  "Challenges", players_path, class:"dropdown-item" %>
                  <%= link_to  "Leaderboards", rankings_path, class:"dropdown-item" %>
                  <hr>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
                </div>
              </li>
            </div>
            <hr>
            <div class="my-2 hide-on-large">
              <div id="notif-mobile">
                <%= link_to "Profile", profile_path(current_user), class:"dropdown-item" %>
                <%= link_to  "Buddies", my_friends_path, class:"dropdown-item" %>
                <hr>
                <%= link_to  "Games", matches_path(user_id: current_user.id), class:"dropdown-item" %>
                <%= link_to  "Challenges", players_path, class:"dropdown-item" %>
                <%= link_to  "Leaderboards", rankings_path, class:"dropdown-item" %>
                <hr>
                <%= link_to "Logout", destroy_user_session_path, class:"dropdown-item", method: :delete %>
              </div>
            </div>
          </ul>
        </div>

        <% else %>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <div class="pl-3 column-on-mobile">
            <div class="align-items-center">
            <ul class="navbar-nav mr-0" id="home-white-links">
              <!-- HOME PAGE - USER NOT LOGGED IN -->
              <% if @white_links == true %>
                <li class="nav-item mx-4 mt-2 d-flex align-items-center">
                  <%= link_to  "Browse games", matches_path, class:"white" %>
                </li>
                <li class="nav-item d-flex align-items-center mx-4 mt-2">
                  <%= link_to  "Login", new_user_session_path, class:"white" %>
                </li>
              <% else %>
                <li class="nav-item mx-4 mt-2 d-flex align-items-center">
                  <%= link_to  "Browse games", matches_path %>
                </li>
                <li class="nav-item d-flex align-items-center mx-4 mt-2">
                  <%= link_to  "Login", new_user_session_path %>
                </li>
              <% end %>
              <li class="nav-item ml-4 mt-2" style="margin-right: 4vw;">
                <%= link_to  "Create game", new_match_path, class: "host-service" %>
              </li>
            </ul>
            </div>
          </div>
        </div>
        <% end %>
      </nav>

    <%= yield %>

    </div>

    <!-- FOOTER -->
    <footer>
      <div class="row">
        <%= link_to  "msb", root_path, class: "logo" %>
        <div class="col-sm-12 col-md-6">
          <div>
            <a href="https://github.com/scorcious/msb"><i class="fab fa-github"></i> Github</a>
          </div>
          <div>
              <a href=""><i class="fab fa-instagram"></i> Instagram</a>
          </div>
          <div>
              <a href=""><i class="fab fa-facebook"></i> Facebook</a>
          </div>
          <div>
              <a href=""><i class="fab fa-linkedin"></i> LinkedIn</a>
          </div>
        </div>

        <div class="col-sm-12 col-md-6">
          <div>
            <%= link_to  "Browse all games", matches_path %>
          </div>
          <div>
            <%= link_to  "Browse all users", profiles_path %>
          </div>
          <div>
            <!-- TODO: -->
            <a href="">Terms & Conditions</a>
          </div>
          <div>
            <!-- TODO: -->
            <a href="">Leave Us Feedbacks</a>
          </div>
          <div>
            <!-- TODO: -->
            <%= link_to  "Meet The Creators", contacts_path %>
          </div>
        </div>
      </div>
    </footer>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <script>
      // desktop notif
      const items = document.querySelectorAll(".dropdown-item");
      const buddies = items[1];
      const challenges = items[3];

      // mobile notif
      const mobile = document.querySelector("#notif-mobile").children;
      const buddiesMobile = mobile[1];
      const challengesMobile = mobile[4];

      // Buddies
      buddies.insertAdjacentHTML("beforeend", `
        <% if @buddies_pending_counts != 0 %>
          <span><%= @buddies_pending_counts %></span>
        <% end %>
      `);
      buddiesMobile.insertAdjacentHTML("beforeend", `
        <% if @buddies_pending_counts != 0 %>
          <span><%= @buddies_pending_counts %></span>
        <% end %>
      `);

      // Challenges
      challenges.insertAdjacentHTML("beforeend", `
        <% if @challenges_counts != 0 %>
          <span><%= @challenges_counts %></span>
        <% end %>
      `);
      challengesMobile.insertAdjacentHTML("beforeend", `
        <% if @buddies_pending_counts != 0 %>
          <span><%= @buddies_pending_counts %></span>
        <% end %>
      `);

    </script>
  </body>
</html>